version: '3.8'

services:
  patient_service:
    build:
      context: .
      dockerfile: docker/php/dockerfile
    container_name: patient_service_container
    volumes:
      - ./src:/var/www
    depends_on:
      - patient_db
    expose:
      - "9000"

  patient_nginx:
    image: nginx:alpine
    container_name: patient_nginx_container
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - patient_service

  patient_db:
    image: mysql:8.0
    container_name: patient_db_container
    environment:
      MYSQL_DATABASE: rareCare
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rareCare
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - patient_db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: patient_pma_container
    ports:
      - "8000:80"
    environment:
      PMA_HOST: patient_db
      PMA_USER: rareCare
      PMA_PASSWORD: secret
    depends_on:
      - patient_db

volumes:
  patient_db_data:
